name: chat
description: "Professional Flutter messenger with glassmorphism, offline cache, and multi-platform support."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Бэкенд и Realtime ---
  supabase_flutter: ^2.6.0

  # --- Управление состоянием и локальные настройки ---
  provider: ^6.1.2
  shared_preferences: ^2.2.2

  # --- Локальная БД (ОФФЛАЙН КЭШ) ---
  # sqflite работает на Android/iOS
  sqflite: ^2.3.3+3
  # sqflite_common_ffi необходим для работы базы на Windows
  sqflite_common_ffi: ^2.3.3
  # sqlite3_flutter_libs содержит необходимые .dll для Windows
  sqlite3_flutter_libs: ^0.5.24

  # --- Работа с файловой системой и путями ---
  path: ^1.9.0
  path_provider: ^2.1.2

  # --- Мультимедиа и иконки ---
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.8

  # --- Системные функции ---
  url_launcher: ^6.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Если решишь добавить свои картинки/шрифты, раскомментируй ниже:
  # assets:
  #   - assets/